# -*- coding: utf-8 -*-
"""МАКОКЛЮЕВ ПИ-311 ЛАБОРАТОРНАЯ 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jXl8x-p-0RS3SSSkLojbzh6Z3MLJicwd
"""

# Макоклюев Виталий ПИ-311
# Лабораторная №3. Задание №1.

months = ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"]

def getMonth(num):
    if num > len(months) or num <= 0:
        return None

    return months[num - 1]


inputNum = int(input("Введите порядковый номер месяца от 1 до 12: "))

result = getMonth(inputNum)

if result is not None:
    print(result)
else:
    print("Некорректный порядковый номер")

# Макоклюев Виталий ПИ-311
# Лабораторная №3. Задание №2.

num = int(input("Введите целое число: "))

if num % 2 == 0:
    print(f"Число {num} является четным.")
else:
    print(f"Число {num} является нечетным.")

# Макоклюев Виталий ПИ-311
# Лабораторная №3. Задание №3.

N = int(input("Введите число N: "))

if N > 40:
    print("stonks")
else:
    print("not stonks")

# Макоклюев Виталий ПИ-311
# Лабораторная №3. Задание №4.

def is_year_leap(year):

    if year % 4 == 0:
        if year % 100 == 0:
            if year % 400 == 0:
                return True
            else:
                return False
        else:
            return True
    else:
        return False


print(is_year_leap(2018))
print(is_year_leap(2096))
print(is_year_leap(1845))
print(is_year_leap(1940))
print(is_year_leap(2044))

# Макоклюев Виталий ПИ-311
# Лабораторная №3. Задание №5.
# Проверка на простое число

import math

def is_prime(n):
    if n <= 1:
        return False
    elif n <= 3:
        return True
    else:
        for i in range(2, int(math.sqrt(n)) + 1):
            if n % i == 0:
                return False
        return True

number = int(input("Введите число для проверки:"))
print(f"{number}: {is_prime(number)}")

# Макоклюев Виталий ПИ-311
# Лабораторная №3. Задание №6.

def swap(x, y):
    if x > 3.6 * y:
        return y, x
    elif -6.164 < y < 24.185:
        return y, x
    else:
        return x, y


x = float(input("Введите значение первой переменной: "))
y = float(input("Введите значение второй переменной: "))

swappedValues = swap(x, y)

print(f"Первая переменная: {swappedValues[0]}")
print(f"Вторая переменная: {swappedValues[1]}")

# Макоклюев Виталий ПИ-311
    # Лабораторная №3. Задание №7.

    numbers = list(map(int, input().split()))

    uniqueNumbers = set(numbers)
    if len(uniqueNumbers) == len(numbers):
        print("Все числа уникальны.")
    else:
        print("Некоторые числа дублируются.")

    evenCount = sum(1 for num in numbers if num % 2 == 0)
    print(f"Количество четных чисел: {evenCount}")

    negativeCount = sum(1 for num in numbers if num < 0)
    print(f"Количество отрицательных чисел: {negativeCount}")

    intervalCount = sum(1 for num in numbers if -256 <= num <= 1024)
    print(f"Количество чисел в промежутке [-256 ; 1024]: {intervalCount}")

# Макоклюев Виталий ПИ-311
 # Лабораторная №3. Задание №8.

def solve_inequality(a, b, c):
    numerator = a**2 + b**3
    denominator = c + 3
    quotient = numerator / (denominator / 4)
    return quotient

def is_even(number):
    return number % 2 == 0

def is_odd(number):
    return number % 2 == 1

# Ввод данных
a = int(input("Введите значение a: "))
b = int(input("Введите значение b: "))
c = int(input("Введите значение c: "))

# Решение неравенства
solution = solve_inequality(a, b, c)

# Проверка чётности
if is_even(solution):
    print(f"Ответ ({solution}) является чётным числом.")
elif is_odd(solution):
    print(f"Ответ ({solution}) является нечётным числом.")
else:
    print("Что-то пошло не так.")