# -*- coding: utf-8 -*-
"""МАКОКЛЮЕВ ПИ-311 ЛАБОРАТОРНАЯ №1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q_7_icEBq6MvEuvkh5ydj130pSW2-nj5
"""

# Макоклюев Виталий ПИ-311
# Лабораторная №1. Задание №1.
a = 5
b = int(input("Введите значение b: "))

print(f"Значение b: {b}")

result = a * b
print(f"Произведение a * b равно: {result}")

# Макоклюев Виталий ПИ-311
# Лабораторная №1. Задание №2.


a = int(input("Введите первое число: "))
b = int(input("Введите второе число: "))

sum = a + b

# Возводим сумму в квадрат
squareSum = sum ** 2

# Выводим результат
print(f"Сумма {a} и {b}, возведенная в квадрат, равна {squareSum}.")

# Макоклюев Виталий ПИ-311
# Лабораторная №1. Задание №3.


a = 15
b = 10

C = int(input("Введите значение C: "))

sum = a + b
result = sum / C

print(f"Результат деления суммы {a} и {b} на {C}: {result}")

# Макоклюев Виталий ПИ-311
# Лабораторная №1. Задание №4.

a = int(input("Введите первое число: "))
b = int(input("Введите второе число: "))

sum = a + b
squareSum = sum ** 2

print(f"Квадрат суммы {a} и {b} равен {squareSum}.")

# Макоклюев Виталий ПИ-311
# Лабораторная №1. Задание №5.

side1 = float(input("Введите длину первой стороны: "))
side2 = float(input("Введите длину второй стороны: "))
side3 = float(input("Введите длину третьей стороны: "))

if side1 <= 0 or side2 <= 0 or side3 <= 0:
    raise ValueError("Длины сторон должны быть положительными числами.")


s = (side1 + side2 + side3) / 2
area = s * (s - side1) * (s - side2) * (s - side3)


perimeter = side1 + side2 + side3


print(f"Площадь треугольника: {area:.2f}")
print(f"Периметр треугольника: {perimeter:.2f}")

# Макоклюев Виталий ПИ-311
# Лабораторная №1. Задание №6.


a = float(input("Введите значение a: "))
b = float(input("Введите значение b: "))


result = ((a ** 3 + 14) // 5) * b


print(f"Решение неравенства: {result}")

# Макоклюев Виталий ПИ-311
# Лабораторная №1. Задание №7.


num = int(input("Введите число: "))
divisor = int(input("Введите делитель: "))


squaredNumber = num ** 2
result = squaredNumber // divisor


print(f"{squaredNumber} / {divisor} = {result}")

# Макоклюев Виталий ПИ-311
# Лабораторная №1. Задание №8.



num1 = float(input("Введите первое дробное число: "))
num2 = float(input("Введите второе дробное число: "))

nat1 = int(input("Введите первое натуральное число: "))
nat2 = int(input("Введите второе натуральное число: "))

# Дробное число без остатка
resultNum = num1 // num2

# Умножение натуральных чисел
resultNat = nat1 * nat2

# Вычисляем остаток от деления натуральных чисел
reminderNat = nat1 % nat2

# Выводим результаты
print(f"Результат деления дробных чисел без остатка: {resultNum}")
print(f"Результат умножения натуральных чисел: {resultNat}")
print(f"Остаток от деления натуральных чисел: {reminderNat}")

# Макоклюев Виталий ПИ-311
# Лабораторная №1. Задание №9.

def convert(seconds):
    days = seconds // 86400
    hours = (seconds % 86400) // 3600
    minutes = (seconds % 3600) // 60

    return days, hours, minutes

seconds = int(input("Введите количество секунд: "))
days, hours, minutes = convert(seconds)


print(f"Количество дней: {days}")
print(f"Количество часов: {hours}")
print(f"Количество минут: {minutes}")